spring.application.name=unio

# \u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 PostgreSql
spring.datasource.url=jdbc:postgresql://localhost:5432/unio
spring.datasource.username=postgres
spring.datasource.password=252103G.bulat

# \u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# \u041E\u0442\u043A\u043B\u044E\u0447\u0430\u0435\u043C \u0441\u0442\u0430\u043D\u0434\u0430\u0440\u0442\u043D\u0443\u044E \u0444\u043E\u0440\u043C\u0443 Spring Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# \u0414\u043B\u044F \u0444\u043E\u0442\u043E\u043A
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
app.upload.dir=uploads
